main:
	gcc KunzeTarek_tp23_exo1_v2.c -o exo1b -DTEMPO -lpthread -Wall

e2:
	gcc tp23_exo2_base.c -o exo2b -DTEMPO -lpthread

e3:
	gcc tp23_exo3_base.c -o exo3b -DTEMPO -lpthread -Wall

e4:
	gcc tp23_exo4_base.c -o exo4b -DTEMPO -lpthread -Wall