tp1e2 : tp1v2
	gcc -Wall -Werror -pedantic -o tp1e2 tp1_exo2.c -lpthread

tp1v2 : tp1
	gcc -Wall -Werror -pedantic -o tp1v2 tp1_exo1-v2_base.c -lpthread

tp1: 
	gcc -Wall -Werror -pedantic -o tp1 tp1_exo1-v1_base.c -lpthread

clean:
	rm tp1 tp1v2 tp1e2